### Volumes ###
apiVersion: v1
kind: Pod
metadata:
   name: random-number-generator
spec:
   containers:
   - image: alpine
     name: alpine
	 command: ["/bin/sh","-c"]
	 args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
     volumeMounts:
	 - mountPath: /opt
	   name: data-volume
   volumes:
   - name: data-volume
     hostPath:
	    path: /data
		type: Directory
        
### Persistent Volume ###

#### Create Persistent Volume ####
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-vol1
spec:
  accessModes:
        - ReadWriteOnce #(ReadOnlyMany, ReadWriteMany)
  capacity:
       storage: 1Gi  
  hostPath:
       path: /tmp/data

### Persistent Volume Claim ###

#### Create Persistent Volume Claim ####
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: myclaim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi
            
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
        
kubectl get persistentvolumeclaim
kubectl delete persistentvolumeclaim myclaim