## Download CUDA toolkit tại
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=CentOS&target_version=8&target_type=runfile_local

## Download Driver
https://www.nvidia.com/Download/index.aspx

## Disable Nouveau
lsmod | grep nouveau
cat << EOF >/etc/modprobe.d/nvidia-installer-disable-nouveau.conf
# generated by nvidia-installer
blacklist nouveau
options nouveau modeset=0
EOF
dracut --force

## Khởi động lại máy
reboot

## Cài đặt packages cần thiết để cài driver
yum install pciutils
yum -y install elfutils-libelf-devel pkg-config libglvnd make gcc
sudo yum -y install kernel-devel-$(uname -r) kernel-headers-$(uname -r)
wget http://123.30.212.230:8181/software/NVIDIA-Linux-x86_64-460.73.01-grid.run
chmod +x NVIDIA-Linux-x86_64-460.73.01-grid.run

## Cài đặt Cuda toolkit
chmod +x cuda_11.5.0_495.29.05_linux.run
sh cuda_11.5.0_495.29.05_linux.run

## Cài đặt driver
chmod +x NVIDIA-Linux-x86_64-470.57.02.run
sh NVIDIA-Linux-x86_64-470.57.02.run

## Cài đặt Packages cần thiết:

sudo dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
sudo dnf install nvidia-gds
sudo dnf module install nvidia-driver:latest-dkms
sudo dnf install cuda

## Kiểm tra lại bằng lệnh
lspci | grep -i nvidia

nvidia-smi
